/* SIN BASS DLL | VERSION 1.3.1 */
/* using bass.dll version 2.4.7.1 */

var dll;dll=temp_directory+"\sin-bass.dll"

global._sinbass_init=external_define(dll,"sin_bass_init",dll_cdecl,ty_real,2,ty_string,ty_real)
global._sinbass_get_master_volume=external_define(dll,"sin_bass_get_master_volume",dll_cdecl,ty_real,0)
global._sinbass_set_master_volume=external_define(dll,"sin_bass_set_master_volume",dll_cdecl,ty_real,1,ty_real)
global._sinbass_set_global_volume=external_define(dll,"sin_bass_set_global_volume",dll_cdecl,ty_real,1,ty_real)
global._sinbass_get_global_volume=external_define(dll,"sin_bass_get_global_volume",dll_cdecl,ty_real,0)
global._sinbass_error_get_code=external_define(dll,"sin_bass_error_get_code",dll_cdecl,ty_real,0)
global._sinbass_get_device=external_define(dll,"sin_bass_get_device",dll_cdecl,ty_real,0)
global._sinbass_set_device=external_define(dll,"sin_bass_set_device",dll_cdecl,ty_real,1,ty_real)
global._sinbass_get_cpu=external_define(dll,"sin_bass_get_cpu",dll_cdecl,ty_real,0)
global._sinbass_close=external_define(dll,"sin_bass_close",dll_cdecl,ty_real,0)

global._sinbass_stream_load=external_define(dll,"sin_bass_stream_load",dll_cdecl,ty_real,1,ty_string)
global._sinbass_stream_play=external_define(dll,"sin_bass_stream_play",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_pause=external_define(dll,"sin_bass_stream_pause",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_resume=external_define(dll,"sin_bass_stream_resume",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_loop=external_define(dll,"sin_bass_stream_loop",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_set_loop=external_define(dll,"sin_bass_stream_set_loop",dll_cdecl,ty_real,2,ty_real,ty_real)
global._sinbass_stream_get_loop=external_define(dll,"sin_bass_stream_get_loop",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_stop=external_define(dll,"sin_bass_stream_stop",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_set_volume=external_define(dll,"sin_bass_stream_set_volume",dll_cdecl,ty_real,2,ty_real,ty_real)
global._sinbass_stream_get_volume=external_define(dll,"sin_bass_stream_get_volume",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_set_pitch=external_define(dll,"sin_bass_stream_set_pitch",dll_cdecl,ty_real,2,ty_real,ty_real)
global._sinbass_stream_set_pan=external_define(dll,"sin_bass_stream_set_pan",dll_cdecl,ty_real,2,ty_real,ty_real)
global._sinbass_stream_fade_volume=external_define(dll,"sin_bass_stream_fade_volume",dll_cdecl,ty_real,3,ty_real,ty_real,ty_real)
global._sinbass_stream_fade_pan=external_define(dll,"sin_bass_stream_fade_pan",dll_cdecl,ty_real,3,ty_real,ty_real,ty_real)
global._sinbass_stream_fade_pitch=external_define(dll,"sin_bass_stream_fade_pitch",dll_cdecl,ty_real,3,ty_real,ty_real,ty_real)
global._sinbass_stream_is_playing=external_define(dll,"sin_bass_stream_is_playing",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_is_paused=external_define(dll,"sin_bass_stream_is_paused",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_is_stopped=external_define(dll,"sin_bass_stream_is_stopped",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_volume_is_fading=external_define(dll,"sin_bass_stream_volume_is_fading",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_pitch_is_fading=external_define(dll,"sin_bass_stream_pitch_is_fading",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_pan_is_fading=external_define(dll,"sin_bass_stream_pan_is_fading",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_set_position_bytes=external_define(dll,"sin_bass_stream_set_position_bytes",dll_cdecl,ty_real,2,ty_real,ty_real)
global._sinbass_stream_get_position_bytes=external_define(dll,"sin_bass_stream_get_position_bytes",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_get_position_seconds=external_define(dll,"sin_bass_stream_get_position_seconds",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_get_length_bytes=external_define(dll,"sin_bass_stream_get_length_bytes",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_get_length_seconds=external_define(dll,"sin_bass_stream_get_length_seconds",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_get_pitch=external_define(dll,"sin_bass_stream_get_pitch",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_get_pan=external_define(dll,"sin_bass_stream_get_pan",dll_cdecl,ty_real,1,ty_real)
global._sinbass_stream_free=external_define(dll,"sin_bass_stream_free",dll_cdecl,ty_real,1,ty_real)

global._sinbass_sample_load=external_define(dll,"sin_bass_sample_load",dll_cdecl,ty_real,1,ty_string)
global._sinbass_sample_play=external_define(dll,"sin_bass_sample_play",dll_cdecl,ty_real,1,ty_real)
global._sinbass_sample_stop=external_define(dll,"sin_bass_sample_stop",dll_cdecl,ty_real,1,ty_real)
global._sinbass_sample_free=external_define(dll,"sin_bass_sample_free",dll_cdecl,ty_real,1,ty_real)
global._sinbass_sample_set_volume=external_define(dll,"sin_bass_sample_set_volume",dll_cdecl,ty_real,2,ty_real,ty_real)
global._sinbass_sample_set_pitch=external_define(dll,"sin_bass_sample_set_pitch",dll_cdecl,ty_real,2,ty_real,ty_real)
global._sinbass_sample_set_pan=external_define(dll,"sin_bass_sample_set_pan",dll_cdecl,ty_real,2,ty_real,ty_real)
global._sinbass_sample_get_volume=external_define(dll,"sin_bass_sample_get_volume",dll_cdecl,ty_real,1,ty_real)
global._sinbass_sample_get_pitch=external_define(dll,"sin_bass_sample_get_pitch",dll_cdecl,ty_real,1,ty_real)
global._sinbass_sample_get_pan=external_define(dll,"sin_bass_sample_get_pan",dll_cdecl,ty_real,1,ty_real)

return external_call(global._sinbass_init,working_directory+"\bass.dll",window_handle())
