s = new("Shiroko")
h = new("Hoshino")
c = new("Serika")
n = new("Nonomi")
a = new("Ayane")

h1 = new("Helmet Gangster Black") h1.name = "Helmet Gangster B"
h2 = new("Helmet Gangster Red")   h2.name = "Helmet Gangster A"
h3 = new("Helmet Gangster Black") h3.name = "Helmet Gangster"

music1 = "theme 09"
music2 = "theme 10"
music3 = "theme 05"

//Abydos Residental Area
lb()
    bg("BG Residence") bfi()
    tit("Episode 2", "First Day at Abydos")
    loc("Abydos Residental Area")

    tfi(5)
    sfx("SE Bird 01")
        say("*chirp* *chirp* *chirp*")
        say("???", "Huh?")
    sfx("SE Bikestop 01")
        say("*screech*")
        say("???", "...")
        say("???", "Hmm...")

    mus(music1)
    sfx("SE Ratchet 01") sfw(1) tfo()
    bg("BG CS Abydos 02") bsc(3) wai(1)
    bsc(1, .7) sfn(1) wai(1)

    tfi()
        say("???", "...")
        say("???", "Are you okay?")
        ch ("#1 Nod.", "#2 Ask for help.")

lb(1)
        say(s, "At least you're alive. I thought you were a goner when I saw you lying in the road like that.")
        say(s, "What's that? You fainted from hunger?")
        say(s, "Does that mean you're homeless?")
        say(s, "Oh...")
    lj(3)

lb(2)
        say(s, "You didn't get mugged, did you? Or involved in some kind of accident?")
        say(s, "What's that? You fainted from hunger?")
        say(s, "So you're not homeless?")
        say(s, "Oh...")
    lj(3)

lb(3)
    sfb(2) tfo() bg("BG Residence")
    sfn(2) wai(1)

    loc("Abydos Residental Area")
    tfi() cex(s, 1) cfi(s, 3)
        say(s, "*Glances*")
    cem(s, em_dot)
        say(s, "You came here on business, but fainted out of hunger and dehydration when you couldn't find a single shop open?")
    cex(s, 0) cpf(s, pf_nod)
        say(s, "Well that's hardly surprising.")
        say(s, "It happens all the time around here. It's been a long time since there were businesses open in this neighborhood that offer food and drinks.")
        say(s, "You would have more luck further towards the outskirts.")
    cex(s, 2) cem(s, em_sweat)
        say(s, "You're not sure how to get there? So this must be your first time here.")
    cex(s, 0)
        say(s, "...Hold on.")
    cpf(s, pf_nod) sfx("SE Gear 02")
        say("*rummaging*")

    cfo(s, 3) wai(1) csc(s, 1.5) cfi(s, 3) wai(1.5)
    cex(s, 2) cem(s, em_respond)
        say(s, "Here, have some of my energy drink.")
    cex(s, 0)
        say(s, "It's for cycling, but it's all I have right now. Better than nothing.")
    cfo(s, 3) wai(1) csc(s, 1) cfi(s, 3) wai(0.5) cex(s, 3)
        say(s, "Wait. Let me get you a cup or something.")
    ch ("Drink it straight from the bottle.")

    sfx("SE Cup 01")
        say("*gulp* *gulp*")
    cex(s, 0) cpf(pf_shake) cem(s, em_exclaim)
        say(s, "...!")
    cex(s, 1) cem(s, em_shy)
        say(s, "You weren't supposed to...")
    cex(s, 0)
        say (s, "Never mind. Don't worry about it.")
    ch ("Thank her for coming to your rescue.")

    cem(s, em_sweat)
        say(s, "Um...")
        say(s, "You look like you're an adult from General Student Council.#Are you here on some kind of academy-related business?")
        say(s, "Ours is the only one around.")
    cex(s, 5) cem(s, em_respond)
        say(s, "So you're here to visit Abydos High School?")
    ch ("Nod.")

    cex(s, 0)
        say(s, "Oh. It's been a long time since anyone visited us.")
        say(s, "Let me show you the way. It's right around here.")
    cex(s, 3) cem(s, em_question)
        say(s, "What? Too hungry to move?")
    cex(s, 0)
        say(s, "That's...a problem.")
    ch ("Ask for a ride")

    cex(s, 3) cem(s, em_sweat)
        say(s, "But it only has one seat.")
    ch ("Ask her for a piggyback ride instead.")
    cex(s, 1) cem(s, em_dot)
        say(s, "...")
    cex(s, 0)
        say(s, "Fine. I'd rather do that.")
    cmv(s, 75, 8) sfx("SE Ratchet 01")
        say(s, "Let me just park my bike.")
    cmv(s, 50, 8)
        say(s, "Hop on.")
    sfx("SE Gear 02") cpf(pf_down) wai(0.3) csc(s, 1.5)
        say("*shuffle*")
    cex(s, 3) cem(s, em_exclaim) cpf(pf_shake)
        say(s, "Wait.")
    cex(s, 1) cem(s, em_dot) csc(s, 1)
        say(s, "...")
        say(s, "It's just, I had been cycling for a while. I didn't work up that much of a sweat, but still...")
    cem(s, em_shy)
        say(s, "I usually have to take a shower at school afterward and keep a change of clothes there.")
    cex(s, 3)
        say(s, "Huh? You don't mind?")
    cex(s, 0) cpf(s, pf_shake)
        say(s, "You actually think I smell good?")
    cex(s, 1)
        say(s, "...")
    cex(s, 0) cem(s, em_sweat)
        say(s, "What is anyone is supposed to say to that? Whatever. As long as you're not going to complain.")
        say(s, "Let's go.")
    sfx("SE Gear 02") cpf(pf_down) wai(0.3) csc(s, 1.5)
        say("*shuffle*")
    cex(s, 2) cem(s, em_music)
        say(s, "Hold on tight.")
    mus(0, 2) sfb(1) tfo() csc(s, 1) cmv(s, 120) wai(0.5)

//Abydos Foreclosure Task Force
    bg ("BG CommitteeRoom") sfn(1) wai(0.5)
    loc("Abydos Foreclosure Task Force")
    sfx("SE DoorOpen 02") wai(1.5) mus(music2)
    cex(s, 0) cmv(s, 75, 8) tfi() foc(true)
        say(s, "I'm back.")
    cmv(c, 25) cex(c, 0) cfi(c, 3)
        say(c, "Welcome back, Shiro...ko?")
    cex(c, 10) cem(c, em_surprise) cpf(c, pf_shake)
        say(c, "Who's that riding on your back?!")
    cfo(s) cmv(n, 75) cex(n, 13) cfi(n, 3)
        say(n, "Whoa! Shiroko kidnapped someone!")
    cfo(c) cmv(a, 25) cex(a, 1) cfi(a, 3)
        say(a, "That or it's a dead body! What did you do, Shiroko?!")
    cfo(a) cex(c, 3) cfi(c) cem(c, em_respond) cpf(c, pf_jump)
        say(c, "Everyone, calm down. We have to help her hide the body!#Go grab a shovel and pickaxe from the storage!")
    cfo(n) cex(s, 0) cfi(s) cem(s, em_sweat)
        say(s, "...")
    bpf(pf_shake) sfx("SE Fall 02")
        say("*collapses*")
        say(s, "Settle down -- they're alive and breathing. They just came to visit the school.")
    cfo(c) cex(a, 2) cfi(a) cem(a, em_question)
        say(a, "What? It's not a corpse?")
    cfo(a) cex(c, 0) cfi(c)
        say(c, "A visitor? Are you sure you didn't kidnap them?")
    cem(s, em_sweat)
        say(s, "Uh...")
    ch ("Greet them with a smile.")

    cfo(c) cmv(n, 25) cex(n, 3) cfi(n) cem(n, em_respond)
        say(n, "I'm shocked. We haven't had a visitor in ages.")
    cfo(s) cmv(a, 75) cex(a, 10) cfi(a) cem(a, em_sweat)
        say(a, "True...but were we expecting anyone?")
    cfo(n, 3) cfo(a, 3) wai(1) tfo(5) wai(1)
    ch ('"'+"I'm an advisor with Schale. It's nice to meet you."+'"')

    foc(false)
    cmv(n, 25) cmv(a, 50) cmv(c, 75)
    cex(n, 7) cex(a, 2) cex(c, 0)
    cfi(n, 3) cfi(a, 3) cfi(c, 3)
    cem(n, em_exclaim) cem(a, em_surprise) cem(c, em_exclaim)
    wai(3)

    cex(a, 0) cpf(a, pf_shake) tfi() foc(true)
        say(a, "No way! Are you?!")
    cex(c, 11) cem(c, em_surprise) cpf(pf_shake)
        say(c, "You're with schale? The Federal Investigation Club?!")
    cex(n, 13) cem(n, em_heart) cpf(n, pf_jump)
        say(n, "Wow! That means you got the letter Ayane wrote!")
    cex(a, 8) cpf(a, pf_nod)
        say(a, "This is great. This means we can finally get more ammo and supplies.")
    cex(a, 3) cem(a, em_question)
        say(a, "I have to tell Hoshino. Wait... Where is she anyway?")
    cex(c, 1)
        say(c, "She's taking a nap in the next room. I'll go wake her up.")
    cmv(c, 150, 3) sfx("SE DoorOpen 02") wai(3)

    cfo(n) cfo(a) mus() sfx("SE Rapid 01")
        say("*pop* *pop* *pop* *tat*")
    cex(n, 10) cfi(n, 3) cem(n, em_surprise) cpf(n, pf_shake)
        say(n, "Was that gunfire?!")
    cex(s, 5) cfi(s, 3) cem(s, em_exclaim)
        say(s, "...!")
    mus(music3) sfb(2) tfo() cfo(n) cfo(s)

//Outside
    bg ("BG SchoolFrontGate") sfn(2) wai(1.5)
    cmv(h1, 25) cmv(h3, 75) foc(false)
    cfi(h1, 3) cfi(h2, 3) cfi(h3, 3) wai(1.5)
    cpf(h1, pf_jump) tfi() foc(true)
        say(h1, "Hahaha!")
    cem(h2, em_exclaim)
        say(h2, "They're all out of ammo! Finish 'em off, and then take over the school!")
    cpf(h1, pf_shake) cpf(h2, pf_shake) cpf(h3, pf_shake) sfx("SE Rapid 01") foc(false)
        say("*pop* *pop* *pop* *tat*")
    cmv(h1, -100, 4) cmv(h3, 200, 4) cfo(h2, 2) sfx("SE Run 02") wai(1.5)
    sfb(2) tfo() cfo(h1) cfo(h2)

//Abydos Foreclosure Task Force
    bg ("BG CommitteeRoom") sfn(2)
    cmv(a, 25) cex(a, 2) cfi(a, 3) cem(a, em_surprise) tfi() foc(true)
        say(a, "There's a group approaching the school! It must be the Kata-Kata Helmet Gang!")
    cmv(s, 75) cex(s, 5) cfi(s, 3) cmv(c, 150)
        say(s, "Those punks... They have some nerve coming back for more.")
    cfo(s)
    cmv(h, 75) cex(h, 11) cfi(h, 3)
    cex(c, 11) cfi(c) cmv(c, 60, 6) sfx("SE Run 04")
        say(c, "I've got Hoshino! Now if she'd just wake up!")
    cex(h, 5) cpf(h, pf_shake2)
        say(h, "*yawn* Just five more minutes...")
    cex(a, 1) cem(a, em_exclaim)
        say(a, "Hoshino! The Helmet Gang is attacking again! By the way, this is Sensei from Schale.")
    cex(c, 3) cex(h, 11)
        say(h, "Ohh. That's a problem... *yawn* Nice to meet you, Sensei.")
    cex(h, 5) cpf(c, pf_jump)
        say(c, "Wake up and get your butt in gear, Hoshino! Literally! We have to defend the school!")
    cex(h, 4)
        say(h, "*yawn* Don't they know it's rude to interrupt someone's nap? I hate the Helmet Gang.")
    cfo(a, 3) cfo(c, 3) cfo(h, 3) wai(1)
    cex(s, 5) cfi(s, 3) cpf(s, pf_nod) sfx("SE Reload 02")
        say(s, "Let's get going. Sensei brought us ammo and supplies to use.")
    cmv(n, 25) cex(n, 13) cfi(n, 3) cem(n, em_twinkle)
        say(n, "Okay! Let's sortie, everyone!")
    cmv(n, 200, 4) cmv(s, 200, 4) sfx("SE Run 02") wai(2.5)
    cmv(a, 50) cex(a, 12) cfi(a, 3) cem(a, em_respond)
        say(a, "I'll navigate us from here.")
    cex(a, 6) cpf(pf_nod)
        say(a, "Stay on the back lines and provide support, Sensei!")
    mus(0, 3) sfb(1)
//End
