s = new("Shiroko")

lb()
    mus("theme 02")
    bg("BG Dormitory2") bfi(2)
    loc("Emoticon Test") wai(1)

    cfi(s, 5) wai(2) tfi() lj(1)

lb(1)
    cex(s, 0) cem(s, em_dot)        say(s, "em_dot")
    cex(s, 5) cem(s, em_exclaim)    say(s, "em_exclaim")
    cex(s, 1) cem(s, em_heart)      say(s, "em_heart")
    cex(s, 3) cem(s, em_music)      say(s, "em_music")
    cex(s, 0) cem(s, em_question)   say(s, "em_question")
    cex(s, 6) cem(s, em_respond)    say(s, "em_respond")
    cex(s, 2) cem(s, em_shy)        say(s, "em_shy")
    cex(s, 5) cem(s, em_surprise)   say(s, "em_surprise")
    cex(s, 1) cem(s, em_sweat)      say(s, "em_sweat")
    cex(s, 5) cem(s, em_twinkle)    say(s, "em_twinkle")
    lj(1)
