s = new("Shiroko")
h = new("Hoshino")
c = new("Serika")
n = new("Nonomi")
a = new("Ayane")

music1 = "theme 10"
music2 = "theme 05"
music3 = "theme 11"

lb()
    mus(music1)
    bg("BG CommitteeRoom") bfi()
    tit("Episode 3", "Being an Adult is Amazing!")
    loc("Abydos Foreclosure Task Force Club Room")
    
    foc(true)
    cmv(h, 25) cex(h, 6) cfi(h, 3) cem(h, em_music) tfi(3)
        say(h, "Wow, I can't believe we won! The Helmet Gang seemed pretty determined.")
    cmv(a, 75) cex(a, 11) cfi(a, 3) cem(a, em_sweat)
        say(a, "You shouldn't say that, Hoshino. Those thugs would have taken over the school had we lost.")
    cmv(s, 75) cex(s, 3) cfo(a) cfi(s, 3)
        say(s, "Sensei gave us the edge we needed to turn the tide. We couldn't have done it otherwise.")
    cex(s, 2) cem(s, em_twinkle)
        say(s, "Experience was likely the deciding factor. It was amazing how you handled resources, equipment and support.")
    cex(h, 9)
        say(h, "Sheesh, Shiroko. You sound like you have a schoolgirl crush. Anyway, can I go back to sleep now that it's over?")
    cmv(c, 75) cex(c, 3) cfo(s) cfi(c, 3) cem(c, em_angry) cpf(c, pf_jump)
        say(c, "You shouldn't tease Shiroko like that, Hoshino! Besides, haven't you slept enough today?")
    cmv(n, 25) cex(n, 13) cfo(h) cfi(n, 3) cem(n, em_chat)
        say(n, "Someone got yelled at!")
    cmv(a, 50) cex(a, 9) cfi(a, 3) cem(a, em_sweat)
        say(a, "Haha. Anyway, we should introduce ourselves, Sensei.")
    foc(false)
    cex(n, 3) cex(a, 6) cpf(a, pf_nod) cex(c, 0)
        say(a, "We're the Abydos Foreclosure Task Force.")
    cfo(n, 3) cfo(c, 3)
        say(a, "I'm Ayane, and I'm a first-year in charge of the task force's records and operations.")
    cmv(a, 30, 10) cex(a, 8)
        say(a, "This is Serika, also a first-year.")
    foc(true)
    cmv(c, -50) cex(c, 1) cfi(c) cmv(c, 20, 10) cmv(a, 50, 10) cem(c, em_chat)
        say(c, "Hey.")
    cmv(a, 60, 10) cex(a, 3)
        say(a, "And these are our second-years: Shiroko and Nonomi.")
    cmv(n, 150) cex(n, 3) cfi(n) cmv(c, -50, 10) cmv(n, 80, 10) cmv(a, 30, 10) cem(n, em_heart)
        say(n, "Hello, Sensei!")
    cmv(s, 150) cex(s, 2) cfi(s) cmv(s, 60, 10)
        say(s, "We met before.")
    cex(s, 1) cem(s, em_shy)
        say(s, "Ignore what Hoshino said, okay?")
    cmv(n, 150, 10) cmv(s, 150, 10) cmv(a, 50, 10) cex(a, 8)
        say(a, "And this here is our president.")
    cpf(a, pf_nod)
        say(a, "Hoshino is our lone third-year.")
    cmv(h, -50) cex(h, 4) cfi(h) cmv(h, 20, 10) cmv(a, 70, 10) cem(h, em_music)
        say(h, "Nice to meet you, Sensei.")
    cex(a, 6)
        say(a, "I'm sure you've noticed by now that our school is in crisis. That's why I reached out to Schale for help, and you've already managed to come through for us.")
    cmv(h, -50, 10) cmv(a, 50, 10) cex(a, 8)
        say(a, "Those thugs would have succeeded in taking over the school if not for you. We can't thank you enough.")
    ch("Ask what the Foreclosure Task Force's purpose is.")
    cex(a, 6) cpf(a, pf_nod)
        say(a, "The Foreclosure Task Force's goal is to bring Abydos back to its former glory.")
    cmv(n, 25) cex(n, 3) cfo(n) cfi(n, 3) cem(n, em_respond)
        say(n, "We're the only club in the school where every single student is a member! I mean, we're the only five students at this school, but still...")
    cmv(s, 75) cex(s, 0) cfo(s) cfi(s, 3)
        say(s, "All the others either transferred or dropped out and left town.")
    cex(s, 5) cem(s, em_dot)
        say(s, "I don't blame them for leaving Kivotos entirely, with the state that Abydos is in. And now we have to deal with thugs like the Kata-Kata Helmet Gang trying to take over the school.")
    cex(s, 1)
        say(s, "It's too difficult to defend Abydos on our own, and embarassing to see the state it's in, if I'm being honest...")
    cfo(n, 3) cfo(s, 3) cex(a, 11) cem(a, em_sweat)
        say(a, "If Schale hadn't come to help us, we would have been in real big trouble this time around.")
    cfo(a) cmv(h, 50) cfi(h) cex(h, 4) cpf(h, pf_nod)
        say(h, "Seriously, I figured we were done for once we ran out of supplies. That's some timing you had there, Sensei.")
    cmv(h, 25, 10) cmv(n, 75) cex(n, 13) cfi(n, 3) cem(n, em_twinkle)
        say(n, "At least we don't have to worry about the Helmet Gang anymore! It pays to have adults in high places!")
    cmv(s, 25) cem(s, 3) cfo(h) cfi(s)
        say(s, "No. I'm sure it's only a matter of time before they come back.")
    cmv(c, 75) cex(c, 9) cfo(n) cfi(c)
        say(c, "Yeah, probably. Man, I hate them.")
    cmv(a, 25) cex(a, 4) cfo(s) cfi(a) cem(a, em_upset) cpf(a, pf_shiver)
        say(a, "Who knows how long this will drag out? We have plenty of other things to worry about besides the Helmet Gang.")
    cfo(a, 3) cfo(c, 3) wai(1)
    cmv(h, 50) cex(h, 10) cfo(h) cfi(h, 3) cem(h, em_respond)
        say(h, "I have a plan.")
    cex(c, 3) cfi(c, 3) cem(c, em_surprise) cpf(c, pf_shake)
        say(c, "What the...?! Hoshino came up with a plan?!")
    cex(a, 2) cfi(a, 3) cem(a, em_sweat)
        say(a, "I'm surprised too!")
    cex(h, 11) cem(h, em_chat)
        say(h, "Hey, I know I'm not the best, but that kind of reaction hurts my feelings. I do my part too, you know.")
    cex(c, 8)
        say(c, "Well? Spill it.")
    cex(h, 9)
        say(h, "If history repeats itself, the Helmet Gang will attack again in a few days.")
    cfo(a, 3) cfo(h, 3) cfo(c, 3) wai(1)
    csc(h, 1.5) cfi(h, 3) wai(1) cem(h, em_respond)
        say(h, "So before then, why don't go on the offensive for once? They're probably sulking and vulnerable after that last fight.")
    csc(h, 1) cmv(h, 25) cmv(a, 75) cex(a, 0) cfi(a) cem(a, em_surprise) cpf(a, pf_shiver)
        say(a, "Y-You mean right now?")
    cex(h, 6) cpf(h, pf_nod)
        say(h, "Yeah, now. With Sensei here, we have more than enough supplies to finish the job once and for all.")
    cmv(s, 75) cex(s, 0) cfo(a) cfi(s)
        say(s, "True. The Helmet Gang's base is 30 kilometers from here. We have plenty of time if we leave now.")
    cmv(n, 25) cex(n, 11) cfo(h) cfi(n) cem(n, em_music)
        say(n, "I'm all for it. The last thing they're expecting is for us to strike now.")
    cmv(a, 75) cex(a, 11) cfo(s) cfi(a)
        say(a, "I can't deny that, but...what do you think, Sensei?")
    ch ("I'm on board.")
    cfo(n, 3) cfo(a, 3) wai(1)
    cmv(h, 50) cex(h, 6) cfi(h, 3) cem(h, em_twinkle) cpf(h, pf_nod)
        say(h, "Great! If Sensei if giving us the green light, the let's hurry up and go.")
    cmv(s, 150) cex(s, 2) cfi(s) cmv(s, 75, 8)
        say(s, "Let's strike while the iron is hot.")
    cmv(n, -50) cex(n, 13) cfi(n) cmv(n, 25, 8)
        say(n, "Okay! Let's go!")
    sfb(1) mus(0, 1) wai(1) tfo() cfo(n) cfo(h) cfo(s)
    
//City
    bg("BG CityOffice") sfn(2) mus(music2, 1) wai(1)
    cmv(a, 50) cex(a, 6) cfi(a, 3) sfx("SE Radio 01") tfi()
        say(a, "You're now on the Kata-Kata Helmet Gang's turf.")
    cex(a, 1) cem(a, em_respond)
        say(a, "I'm detecting their signal within a 15 kilometer radius.")
    csc(a, 1.5) cex(a, 12) //sfx("UI Start 01")
        say(a, "They must know you're there. Don't let your guard down!")
    mus(0, 3) sfb(1) cfo(a) tfo() wai(2)
// --- Game battle ---

//After battle
    bg("BG CityOffice") sfn(1) mus(music3, 1) wai(1)
    csc(a, 1) cex(a, 6) cfi(a, 3) tfi() sfx("SE Radio 01")
        say(a, "They're retreating!")
    cex(a, 8) cem(a, em_twinkle)
        say(a, "Better yet, the Helmet Gang's supplies, hideout, and ammunition were all taken out.")
    cmv(s, 75) cex(s, 0) cfi(s, 3)
        say(s, "I bet they'll think twice before attacking us again.")
    cmv(h, 25) cex(h, 4) cfi(h, 3)
        say(h, "Great work, everyone. You too, Sensei.")
    cmv(s, 150, 8) cmv(a, 150, 8) cmv(h, 50, 8) cex(h, 12) cem(h, em_music)
        say(h, "Let's head back to the school.")
    tfo(3) wai(.5) tbc() cfo(h)
    bsc(1.5) bg("BG SchoolFrontGate") bsc(1, 1) sfn(3)
    tit("Next Episode", "The Task Force's Predicament")
    sfb(2) mus(0, 4) wai(4)
    fin()
//End
