s = new("Shiroko")

lb()
    mus("theme 02")
    bg("BG Dormitory2") bfi()
    loc("Testing Scene")

    cex(s, 0) cfi(s, 5) tfi()
    say("Apis035", "Dev", "Which type of test?")
    ch ("#1 Perform Animation", "#2 Emoticon")
    
lb(1)
    cpf(s, pf_jump)       say(s, "pf_jump")
    cpf(s, pf_shiver)     say(s, "pf_shiver")
    cpf(s, pf_shake) cem(s, em_exclaim) say(s, "pf_shake")
    cpf(s, pf_nod)        say(s, "pf_nod")
    lj(1)

lb(2)
    cem(s, em_dot)        say(s, "em_dot")
    cem(s, em_exclaim)    say(s, "em_exclaim")
    cem(s, em_heart)      say(s, "em_heart")
    cem(s, em_music)      say(s, "em_music")
    cem(s, em_question)   say(s, "em_question")
    cem(s, em_respond)    say(s, "em_respond")
    cem(s, em_shy)        say(s, "em_shy")
    cem(s, em_surprise)   say(s, "em_surprise")
    cem(s, em_sweat)      say(s, "em_sweat")
    cem(s, em_twinkle)    say(s, "em_twinkle")
    lj(2)

lb(3)
    wai(2)
