s = new("Shiroko")
h = new("Hoshino")
c = new("Serika")
n = new("Nonomi")
a = new("Ayane")

music1 = "theme 10"
music2 = "theme 09"
music3 = "theme 11"

lb()
    mus(music1)
    bg("BG CommitteeRoom") bfi()
    tit("Episode 4", "The Task Force's Predicament")
    loc("Foreclosure Task Force Club Room")

    foc(true)
    cmv(a, 75) cex(a, 6) cfi(a, 3) cpf(a, pf_nod) cem(a, em_respond) tfi()
        say(a, "Welcome back, everyone. Great work today.")
    cmv(h, 25) cex(h, 4) cfi(h, 3)
        say(h, "We're back!")
    cmv(c, 25) cex(c, 1) cfo(h) cfi(c, 3)
        say(c, "Thanks, Ayane. You too.")
    cmv(n, 75) cex(n, 13) cfo(a) cfi(n, 3) cem(n, em_music)
        say(n, "We finally took down the Kata-Kata Helmet Gang. It should be smooth sailing from here.")
    cmv(s, 75) cex(s, 0) cfo(n) cfi(s, 3)
        say(s, "More like we can finally get back to more important matters.")
    cex(c, 6) cem(c, em_chat)
        say(c, "Haha! All we have to focus on now is paying back the debt!")
    cex(c, 1) cpf(c, pf_nod)
        say(c, "Thanks for your help, Sensei. We won't forget what you did for us!")
    cfo(s, 3) cfo(c, 3) tfo(3) wai(1) mus(0, 1)
    ch('"Debt?"')
    cex(c, 10) cfi(c, 3) cem(c, em_surprise) cpf(c, pf_shake) tfi()
        say(c, "Wait... Shoot!")
    cex(a, 11) cfi(a, 3) mus(music2, 1)
        say(a, "W-Well, the thing is...")
    cex(c, 11) cpf(c, pf_shake)
        say(c, "Stop right there! Not another word, Ayane!")
    cex(a, 2) cem(a, em_exclaim)
        say(a, "...!")
    cmv(h, 75) cex(h, 9) cfo(a) cfi(h)
        say(h, "Why not, Serika? It's not like it's a secret.")
    cex(c, 3) cpf(c, pf_jump)
        say(c, "That doesn't mean we should go telling everyone!")
    cex(h, 10)
        say(h, "It isn't as though we're guilty of anything. Besides, Sensei is one of us now.")
    cex(s, 0) cfo(h) cfi(s) cpf(s, pf_nod)
        say(s, "Hoshino is right, Serika. Sensei is responsible--trustworthy, even.")
    cex(c, 2) cem(c, em_angry)
        say(c, "I know, but they're still an outsider.")
    cex(h, 15) cem(h, em_respond) cfo(s) cfi(h)
        say(h, "I'm not saying Sensei can solve this problem on our behalf, but they're the only adult we have to turn to.")
    cex(h, 9)
        say(h, "Maybe we can come up with a solution if we discuss it with Sensei, even. Or do you have any better ideas, Serika?")
    cex(c, 10) cem(c, em_upset) cpf(c, pf_shiver)
        say(c, "Well...")
    cex(c, 4)
        say(c, "But Sensei just showed up out of nowhere! Why would an adult care about our problems, anyway?")
    cex(c, 3)
        say(c, "We've always taken care of ourselves! Why do we suddenly need to be supervised...?")
    cex(c, 11) cem(c, em_exclaim) cpf(c, pf_shake)
        say(c, "I don't want any part of this!")
    cmv(c, -50, 8) sfx("SE DoorOpen 02") wai(1) cfo(c)
    cex(a, 2) cem(a, em_surprise) cfo(h) cfi(a)
        say(a, "Serika?")
    cmv(n, 25) cex(n, 10) cfi(n, 3)
        say(n, "I'll go talk to her.")
    cmv(n, -50, 8) wai(1) cfo(n)
    sfb(2) cfo(a) tfo() wai(1) sfn(2)
    cmv(h, 50) cex(h, 15) cfi(h, 3) cem(h, em_dot) tfi()
        say(h, "...")
    cex(h, 10)
        say(h, "Back to the matter at hand... Our school owes quite a bit of money to a loan company. It's a challenge, but not exactly an uncommon problem either.")
    cex(h, 17) cem(h, em_sweat)
        say(h, "The real issue is...that's it's over 900 million yen.")
    cmv(a, 150) cfi(a) cmv(h, 25, 6) cmv(a, 75, 6) cex(a, 4)
        say(a, "It's 962,350,000 yen, to be exact.")
    cex(a, 5) cem(a, em_dot)
        say(a, "That's the amount that Abydos--no. That's the amount the Foreclosure Task Force has taken upon itself to pay back.")
    cex(a, 11)
        say(a, "The loan company will foreclose the school and shutter it permanently if we don't pay them.")
    cex(a, 4) cem(a, em_upset) cpf(a, pf_shiver)
        say(a, "But the odds of paying back a debt that large are practically zero. That's why most of the students left the school and town...")
    cmv(s, 25) cex(s, 0) cfo(h) cfi(s)
        say(s, "All except us, that is.")
    cex(a, 1)
        say(a, "The debt is the source of everything that's wrong. It's why the school is on the brink of closure, why the students left, and why the town is so desolate...")
    ch("Ask about what happened.")
    cex(a, 0)
        say(a, "You mean how the debt was accrued in the first place?")
    sfb(2) cfo(s) cfo(a) tfo()

    bg("BG DesertResidence") sfn(2) foc(false)
    sfx("SE DustWind 01") wai(1) tfi()
        say(a, "Several years ago, there was a sandstorm in the desert around the school.")
        say(a, "Sandstorms are common in the Abydos region, but that particular storm was devastating.")
        say(a, "Some areas were completely buried in sand, and it just kept pilling up.")
        say(a, "The school had to raise a lot of funds for disaster relief...")
        say(a, "...but there wasn't a single bank that would give such a large loan.")
    sfb(2) tfo() cex(s, 0) cex(a, 5) cfi(s) cfi(a)
    
    bg("BG CommitteeRoom") sfn(2) wai(1) tfi() foc(true)
        say(s, "So the school was forced to turn to loan sharks...")
        say(a, "Exactly. They were looking to take the easy way out and pay the money back quickly...")
    cex(a, 1)
        say(a, "...but the sandstorms only worsened as the years went on. Despite the school's best intentions, the situation just kept getting worse.")
    cex(a, 4) cem(a, em_dot)
        say(a, "Today, more than half of Abydos is under sand and the debt keeps growing.")
    cmv(h, 25) cex(h, 15) cfo(s) cfi(h)
        say(h, "...")
    cex(s, 5) cfo(h) cfi(s)
        say(s, "...")
    cex(a, 11)
        say(a, "We're barely able to pay the interest every month, and now we're all out of ammunition and supplies.")
    cex(s, 3)
        say(s, "I can sympathize with Serika's frustrations. No one has ever cared enough to ask about our situation before, let alone reach out to help.")
    cmv(h, 75) cex(h, 8) cfo(a) cfi(h)
        say(h, "That's the long and short of it.")
    cex(h, 4) cem(h, em_respond)
        say(h, "Now that you've helped us scare the Helmet Gang away, we can return our focus to paying off the debt.")
    cex(h, 11)
        say(h, "Even if we appoint you as our club's advisor, you don't have to trouble yourself with our debt. Just the fact that you've heard our story is enough.")
    cpf(s, pf_nod)
        say(s, "We're not trying to pressure you. You've already helped us enough.")
    cfo(s, 3) cfo(h, 3) tfo(3) wai(1)
    ch("Say you're a member of the task force and they should cheer up.", "Say you'll never abandon the Foreclosure Task Force.")
    cmv(a, 50) cex(a, 2) cfi(a, 3) tfi()
        say(a, "You don't have to say all that...")
    cex(a, 6) cem(a, em_twinkle) cpf(a, pf_nod)
        say(a, "...but thank you for doing so anyway, Sensei.")
    cmv(h, 25) cex(h, 4) cmv(a, 75, 6) cex(a, 0) cfi(h, 3)
        say(h, "Listen to you be so noble. You're really going to insist on helping...")
    cex(a, 8)
        say(a, "I feel so relieved. There's some hope if we have Schale's support.")
    cmv(s, 25) cex(s, 1) cfo(h) cfi(s)
        say(s, "True. Things are looking up, at least.")
    sfb(2) cfo(s) cfo(a) wai(0.5) tfo()

    bg("BG ClassCorridor") sfn(2) wai(1) foc(false)
    cmv(c, 50) cex(c, 9) cfi(c, 3) tfi()
        say(c, "...")
    cex(c, 3) cpf(c, pf_shiver)
        say(c, "Hmph.")
    cmv(c, 150, 8) wai(1) sfb(1) tfo()
    bg("BG SchoolFrontGate") sfn(1) wai(0.5)
    cmv(n, 50) cex(n, 7) cfi(n, 3) wai(2)
    cmv(n, 30, 6) wai(2) cmv(n, 60, 6) wai(2)
    cex(n, 15) cem(n, em_dot) tfi()
        say(n, "Serika, where are you?")
    tfo(3) wai(0.5) tbc() cfo(n)
    bsc(1.5) bg("BG RamenYa") bsc(1, 1) sfn(3)
    tit("Next Episode", "A Day in the Life of Serika")
    sfb(2) mus(0, 4) wai(4)
    fin()
