var dll;dll=temp_directory+'\gmconsole.dll'
global._console_init=external_define(dll,'init',dll_stdcall,ty_string,0)
global._console_read=external_define(dll,'read',dll_stdcall,ty_string,0)
global._console_print=external_define(dll,'print',dll_stdcall,ty_string,1,ty_string)
global._console_title=external_define(dll,'SetTitle',dll_stdcall,ty_string,1,ty_string)
global._console_color=external_define(dll,'color',dll_stdcall,ty_string,1,ty_real)
global._console_free=external_define(dll,'free',dll_stdcall,ty_string,0)
global._console_hide=external_define(dll,'hide',dll_stdcall,ty_real,1,ty_real)
global._console_show=external_define(dll,'unhide',dll_stdcall,ty_real,1,ty_real)
return external_call(global._console_init)
