setPage(0, "Blue Archive S")
    addButton("Story Mode",         gotoPage(1))
    addDimButton("Resource Viewer", showMsg("Currently not available."))
    addButton("Settings",           gotoPage(3))
    addButton("About",              showMsg("Blue Archive S, a clone of Blue Archive's story mode."))
    addButton("Quit Game",          "game_end()")
    addButton("")
    addButton("Open Website",       "execute_shell('https://github.com/Apis035/Blue-Archive-S', 0)")

setPage(1, "Story Mode")
    addDimButton("Prologue",        showMsg("Coming soon."))
    addButton("Chapter 1",          gotoPage(2))
    addDimButton("Chapter 2",       showMsg("Coming soon."))
    addDimButton("Chapter 3",       showMsg("Coming soon."))
    addDimButton("Chapter 4",       showMsg("Coming soon."))
    addButton("")
    addButton("Test Scene",         gotoScene("sceneTest"))
    addButton("")
    addButton("Back",               gotoPage(0))

setPage(2, "Chapter 1")
    addButton("Episode 1 (Broken)", showMsg("This episode is unfinished.") + gotoScene("scene00"))
    addButton("Episode 2",          gotoScene("scene01"))
    addButton("Episode 3",          gotoScene("scene02"))
    addButton("Episode 4",          gotoScene("scene03"))
    addButton("")
    addButton("Back",               gotoPage(1))

setPage(3, "Settings")
    addButton("Fullscreen: " + fi(window_get_fullscreen(), "Enabled", "Disabled"))
    addButton("BGM Volume: " + string(global.BgmVolume * 100) + "%")
    addButton("SFX Volume: " + string(global.SfxVolume * 100) + "%")
    addButton("")
    addButton("Back",               gotoPage(0))
